#
# Copyright (C) 2016 MYIR Tech Ltd - http://www.myirtech.com//
#
# Author: Sunny Guo <sunny.guo@myirtech.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	+= myd_y335x.o
obj-$(CONFIG_SPL_BUILD) += mux.o spl.o
